### ISSUE TITLE
Congratulations On Your First Milestone! 🥂

### ISSUE THREAD

**Issue by kinderasteroid** [varshavshetty/varshavshetty#1]
Hello @varshavshetty, Congratulations on your first achievement as Documentation Head. We would Like to Medal you a GitHub badge which You can showcase on your Personal Profile(i.e. on readme). The same is been reflected in organization's main page as well

Badge Link: 
https://img.shields.io/badge/Documentation_Head-KinderNeutron-506365?style=for-the-badge&logo=pagekit&labelColor=FF1E0D

Keep Charming and Would Love to See your Support!🚀

> PS: Your Can Close This Issue, Once you Read It

**Comment by varshavshetty** [comment]
Thank you so much ✨🎉
